/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zadanie4;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.Point2D;
import javax.swing.Timer;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lesze
 */
public class Zadanie4 extends javax.swing.JFrame {
    
    Lotnisko l1, l2, l3;
    Samolot[] s = new Samolot[6];
    public DefaultTableModel model;
    boolean zatrzymane = false;

    /**
     * Creates new form Zadanie4
     */
    public Zadanie4() {
        initComponents();

        //lotniska
        l1 = new Lotnisko("WAW", new Point2D.Double(20.967100143399996, 52.1656990051));
        l2 = new Lotnisko("LHR", new Point2D.Double(-0.461941, 51.4706));
        l3 = new Lotnisko("JFK", new Point2D.Double(-73.77890015, 40.63980103));
        
        //samoloty
        s[0] = new Samolot(1, l1, l2);
        s[1] = new Samolot(2, l1, l3);
        s[2] = new Samolot(3, l2, l1);
        s[3] = new Samolot(4, l2, l3);
        s[4] = new Samolot(5, l3, l1);
        s[5] = new Samolot(6, l3, l2);
        
        for (int i = 0; i < s.length; i++) {
            s[i].start();
        }
        
        String[] kolumny = {"Kod lotu",
                            "Status lotu"};
        Object[][] dane = {
            { s[0].getKod(), s[0].getStatus() },
            { s[1].getKod(), s[1].getStatus() },
            { s[2].getKod(), s[2].getStatus() },
            { s[3].getKod(), s[3].getStatus() },
            { s[4].getKod(), s[4].getStatus() },
            { s[5].getKod(), s[5].getStatus() },
        };        
        model = new DefaultTableModel(dane, kolumny);
        jTable1.setModel(model);
        
        
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                                Object[][] dane = {
                    { s[0].getKod(), s[0].getStatus() },
                    { s[1].getKod(), s[1].getStatus() },
                    { s[2].getKod(), s[2].getStatus() },
                    { s[3].getKod(), s[3].getStatus() },
                    { s[4].getKod(), s[4].getStatus() },
                    { s[5].getKod(), s[5].getStatus() },
                };
                model.setDataVector(dane, kolumny);
                jTable1.repaint();
            }
        });
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jToggleButton1.setText("Zatrzymaj");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addGap(204, 204, 204))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jToggleButton1)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed

            // TODO add your handling code here:
            if (zatrzymane == false) {
                s[0].suspend();
                s[1].suspend();
                s[2].suspend();
                s[3].suspend();
                s[4].suspend();
                s[5].suspend();
                zatrzymane = true;
                jToggleButton1.setText("Wznów");
            }
            else {
                s[0].resume();
                s[1].resume();
                s[2].resume();
                s[3].resume();
                s[4].resume();
                s[5].resume();
                zatrzymane = false;
                jToggleButton1.setText("Zatrzymaj");
            }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Zadanie4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Zadanie4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Zadanie4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Zadanie4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Zadanie4().setVisible(true);
            }
        });
        
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
